cart/urls.py
# Django imports
from django.urls import path

# Internal imports
from .views import (
    CartView,
    AddToCartView,
    UpdateCartView,
    DeleteCartView,
    CartChoiceView
)

urlpatterns = [
    path(
        '',
        CartView.as_view(),
        name='cart'
    ),

    path(
        'add/<item_id>/',
        AddToCartView.as_view(),
        name='add_to_cart'
    ),

    path(
        'update/<item_id>/',
        UpdateCartView.as_view(),
        name='update_cart'
    ),

    path(
        'delete/<item_id>/',
        DeleteCartView.as_view(),
        name='delete_cart'
    ),

    # User chooses if they want to keep database or session cart, or merge both
    path(
        'select/',
        CartChoiceView.as_view(),
        name='cart_choice'
    ),
]

coffee_hub/urls.py
# Django imports
from django.contrib import admin
from django.urls import path, include, reverse_lazy

# Internal imports
from .views import (
    Custom404View,
    Custom401View,
    set_cookie_consent,
    reset_cookie_consent,
    render_toast_template,
    robots_txt,
    sitemap_xml
)


urlpatterns = [
    # Home app URLs
    path(
        '',
        include('store.urls')
    ),

    # Admin panel
    path(
        "admin/",
        admin.site.urls,
        name='admin'
    ),

    # Authentication and account management
    # Third-party auth package
    path(
        'accounts/',
        include('allauth.urls')
    ),

    # Apps
    # Custom account-related URLs
    path(
        'accounts/',
        include('accounts.urls')
    ),

    # Products
    path(
        'products/',
        include('product.urls')
    ),

    # Cart
    path(
        'cart/',
        include('cart.urls')
    ),

    # Checkout
    path(
        'checkout/',
        include('checkout.urls')
    ),

    # Custom error pages
    # 404 - not found
    path(
        '404/',
        Custom404View.as_view(),
        name='custom_404'
    ),

    # 401 - not permitted
    path(
        '401/',
        Custom401View.as_view(),
        name='custom_401'
    ),

    # Cookies consent
    # Set cookies
    path(
        'set-cookie-consent/',
        set_cookie_consent,
        name='set_cookie_consent'
    ),

    # Reset cookies
    path(
        'reset-cookie-consent/',
        reset_cookie_consent,
        name='reset_cookie_consent'
    ),

    # Toast messages
    path(
        'render-toast/',
        render_toast_template,
        name='render_toast'
    ),

    # Robots.txt
    path(
        'robots.txt',
        robots_txt,
        name='robots_txt'
    ),

    # Sitemap.xml
    path(
        'sitemap.xml',
        sitemap_xml,
        name='sitemap_xml'
    ),
]

product/urls.py
# Django imports
from django.urls import path

# Internal imports
from .views import (
    ProductListView,
    ProductDetailView,
    ProductDeactivateView,
    ReviewSilenceToggler,
    VariantDeactivateView,
    SaveSelector,
    ProductSaveView,
    ProductCreateView
)

urlpatterns = [
    path(
        '',
        ProductListView.as_view(),
        name='product'
    ),

    path(
        'create/',
        ProductCreateView.as_view(),
        name='product_create'
    ),

    path(
        'save/',
        ProductSaveView.as_view(),
        name='product_save'
    ),

    path(
        '<int:pk>/deactivate/',
        ProductDeactivateView.as_view(),
        name='product_deactivate'
    ),

    path(
        'variant/<int:pk>/deactivate/',
        VariantDeactivateView.as_view(),
        name='variant_deactivate'
    ),

    path(
        'reviews/toggle-silence/<int:review_id>/',
        ReviewSilenceToggler.as_view(),
        name='toggle_silence'
    ),

    path(
        '<str:selector_type>/save/',
        SaveSelector.as_view(),
        name='save_selector'
    ),

    path(
        '<slug:slug>/',
        ProductDetailView.as_view(),
        name='product_detail'
    ),
]

product/models.py
import re

# Django imports
from django.db import models
from django.urls import reverse
from django.templatetags.static import static
from django.conf import settings
from django.db.models import Avg

# Third-party imports
from cloudinary.models import CloudinaryField
from cloudinary.api import resource
from cloudinary.exceptions import NotFound
from cloudinary.utils import cloudinary_url

# Internal imports
from django.core.validators import MinValueValidator


class Category(models.Model):
    '''
    Model representing a product category.

    Attributes:
        name (str): The name of the category.
        slug (str): The unique slug identifier for the category.
        created_at (datetime): Timestamp for when the category was created.
    '''
    name = models.CharField(
        max_length=20,
        unique=True,
        blank=False,
        null=False
    )

    slug = models.SlugField(
        unique=True,
        blank=False,
        null=False,
        editable=False
    )

    created_at = models.DateTimeField(auto_now_add=True)

    def save(self, *args, **kwargs):
        '''
        Override the save method to generate a clean slug from the name.
        '''
        clean_name = re.sub(r'[^\w\s-]', '', self.name)
        clean_name = clean_name.replace('-', '_').replace(' ', '_')
        self.slug = clean_name.lower()
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'


class Product(models.Model):
    '''
    Model representing a product.

    Attributes:
        name (str): The name of the product.
        slug (str): The unique slug identifier for the product.
        category (Category): The associated category for the product.
        description (str): A short description of the product.
        rating (float): The average rating of the product.
        image_path (CloudinaryField): The image of the product.
        active (bool): Whether the product is active.
        created_at (datetime): Timestamp for when the product was created.
        updated_at (datetime): Timestamp for when the product was last updated.
    '''
    name = models.CharField(
        max_length=35,
        unique=True,
        blank=False,
        null=False
    )

    slug = models.SlugField(
        unique=True,
        blank=False,
        null=False,
        editable=False
    )

    category = models.ForeignKey(
        Category,
        on_delete=models.CASCADE,
        related_name='products',
        blank=False, null=False
    )

    description = models.TextField(
        blank=True,
        null=True,
        max_length=70
    )

    rating = models.FloatField(
        default=0,
        help_text='Average rating (0-5).'
    )

    image_path = CloudinaryField(
        'image',
        blank=True,
        null=True
    )

    active = models.BooleanField(
        default=True,
        help_text='Set to False to deactivate the product.',
        blank=False,
        null=False
    )

    cloudinary_version = models.CharField(
        max_length=20,
        blank=True,
        null=True
    )

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        '''
        Override the save method to generate a slug and update ratings.

        Preserves existing 'active' status and ensures category consistency.
        '''
        if self.pk:
            original = Product.objects.get(pk=self.pk)
            if not hasattr(self, 'active'):
                self.active = original.active

        if self.name:
            clean_name = re.sub(r'[^\w\s-]', '', self.name)
            clean_name = clean_name.replace('-', '_').replace(' ', '_')
            self.slug = clean_name.lower()

        super().save(*args, **kwargs)

        if self.pk:
            self.rating = self.average_rating
            super().save(update_fields=['rating'])

    def image(self, view=None):
        '''
        Retrieve the product image URL or return a placeholder if unavailable.
        If the view is 'list', return a thumbnail version of the image.

        Args:
            view (str): The view context (e.g., 'list' or 'detail').

        Returns:
            str: The URL of the product image or a static placeholder.
        '''
        try:
            # Access the CLOUD_NAME from settings.CLOUDINARY_STORAGE
            cloud_name = settings.CLOUDINARY_STORAGE['CLOUD_NAME']

            if self.image_path:
                public_id = (
                    self.image_path.public_id
                    if hasattr(self.image_path, 'public_id')
                    else str(self.image_path)
                )

                version = self.cloudinary_version or None

                # Use the 'Thumbnail' transformation for the list view
                if view == 'list':
                    transformation = "t_Thumbnail/"
                else:
                    transformation = ""

                url = (
                    f"https://res.cloudinary.com/{cloud_name}/image/upload/"
                    f"{transformation}v{version}/{public_id}"
                )
                return url
        except Exception:
            return static('images/product-holder.webp')

        return static('images/product-holder.webp')

    def get_buy_url(self):
        '''
        Return the URL for purchasing the product.
        '''
        return reverse('product')

    def get_card_context(self):
        '''
        Generate context for rendering the product card.

        Returns:
            dict: Context with stock, size, price, and status details.
        '''
        variants = self.variants.all()
        stock_by_size = {
            variant.size: {'price': variant.price, 'stock': variant.stock}
            for variant in variants
        }

        default_size = variants[0].size if variants else None
        default_price = (
            stock_by_size[default_size]['price'] if default_size else 0
        )
        default_stock_status = (
            'In Stock'
            if default_size and stock_by_size[default_size]['stock'] > 0
            else 'Out of Stock'
        )

        return {
            'product': self,
            'stock_by_size': stock_by_size,
            'default_size': default_size,
            'default_price': default_price,
            'default_stock_status': default_stock_status,
        }

    def get_absolute_url(self):
        '''
        Return the absolute URL for the product detail view.
        '''
        return reverse('product_detail', kwargs={'slug': self.slug})

    @property
    def average_rating(self):
        '''
        Calculate and return the average product rating.

        Returns:
            float: Rounded average rating or 0.0 if no ratings exist.
        '''
        avg = self.reviews.aggregate(average=Avg('rating'))['average']
        return round(avg, 1) if avg else 0.0


class ProductVariant(models.Model):
    '''
    Model representing a product variant.

    Attributes:
        product (Product): The associated product.
        size (str): The size of the product variant.
        price (Decimal): The price of the variant.
        stock (int): The stock quantity of the variant.
        active (bool): Whether the variant is active.
    '''
    product = models.ForeignKey(
        Product,
        on_delete=models.CASCADE,
        related_name='variants',
        blank=False,
        null=False
    )

    size = models.CharField(
        max_length=10,
        blank=False,
        null=False
    )

    price = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        blank=False,
        null=False,
        validators=[MinValueValidator(0)]
    )

    stock = models.PositiveIntegerField(
        default=0,
        blank=False,
        null=False
    )

    active = models.BooleanField(
        default=True,
        help_text='Set to False to deactivate the size.',
        blank=False,
        null=False
    )

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.product.name} - {self.size}'

    class Meta:
        unique_together = ('product', 'size')


class ProductReview(models.Model):
    '''
    Model representing a product review.

    Attributes:
        product (Product): The reviewed product.
        user (User): The user who submitted the review.
        rating (int): The review rating (0-5).
        comment (str): A short review comment.
        silenced (bool): Whether the review is silenced.
        created_at (datetime): Timestamp for when the review was created.
    '''
    product = models.ForeignKey(
        Product, on_delete=models.CASCADE, related_name='reviews',
        blank=False, null=False
    )

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE,
        blank=True, null=True
    )

    rating = models.IntegerField(
        help_text='Integer rating 0-5', blank=False, null=False
    )

    comment = models.CharField(
        max_length=100, blank=True,
        help_text='Short review (max 100 chars)'
    )

    silenced = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return (
            f'Review of {self.product.name} by '
            f'{self.user if self.user else 'Anonymous'}: {self.rating}'
        )

product/forms.py
# Django imports
from django import forms

# Internal imports
from .models import Product, ProductVariant, ProductReview


class ProductEditForm(forms.ModelForm):
    '''
    Form for editing product details.

    Includes fields for name, description, image, category, and activity
    status.
    '''
    class Meta:
        model = Product

        fields = [
            'name',
            'description',
            'image_path',
            'category',
            'active'
        ]

        widgets = {
            'name': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Enter product name'
            }),
            'description': forms.Textarea(attrs={
                'class': 'form-control',
                'rows': 3,
                'placeholder': 'Enter product description'
            }),
            'image_path': forms.FileInput(attrs={
                'class': 'form-control',
                'accept': 'image/*',
            }),
            'category': forms.Select(attrs={
                'class': 'form-select'
            }),
        }

    def __init__(self, *args, **kwargs):
        '''
        Initialize the form with model values as the default.
        '''
        super().__init__(*args, **kwargs)


class ProductVariantForm(forms.ModelForm):
    '''
    Form for editing product variants.

    Includes fields for size, price, and stock.
    '''
    class Meta:
        model = ProductVariant

        fields = [
            'size',
            'price',
            'stock'
        ]

        widgets = {
            'size': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Enter size'
            }),
            'price': forms.NumberInput(attrs={
                'class': 'form-control',
                'placeholder': 'Enter price',
                'step': 0.01
            }),
            'stock': forms.NumberInput(attrs={
                'class': 'form-control',
                'placeholder': 'Enter stock quantity',
                'min': 0
            }),
        }

    def __init__(self, *args, **kwargs):
        '''
        Initialize the form with model values as the default.

        If an instance is provided, populate the initial values for
        size, price, and stock.
        '''
        instance = kwargs.get('instance')
        super().__init__(*args, **kwargs)
        if instance:
            self.fields['size'].initial = instance.size
            self.fields['price'].initial = instance.price
            self.fields['stock'].initial = instance.stock


class ProductReviewForm(forms.ModelForm):
    '''
    Form for submitting product reviews.

    Includes fields for rating and a short comment.
    '''
    class Meta:
        model = ProductReview

        fields = [
            'rating',
            'comment'
        ]

        widgets = {
            'rating': forms.NumberInput(attrs={
                'min': 0,
                'max': 5,
                'step': 1,
                'required': True,
            }),
            'comment': forms.Textarea(attrs={
                'maxlength': 100,
                'rows': 2,
                'placeholder': 'Write a short comment...'
            }),
        }

    def __init__(self, *args, **kwargs):
        '''
        Initialize the form with a default rating value of 0 if the
        form is not bound.
        '''
        super().__init__(*args, **kwargs)
        if not self.is_bound:
            self.fields['rating'].initial = 0

product/templates/product/includes/actions.html
{% if is_admin %}
    {% if view == 'detail' %}
    <div class="col mb-2 btn-group">
        <button type="button" class="btn btn-success save-product-btn mt-2" 
                data-url="{% if product.id %}{% url 'product_save' %}{% else %}{% url 'product_create' %}{% endif %}" 
                data-product-id="{{ product.id }}">
            {% if product.id %}Save{% else %}Create{% endif %}
        </button>
        {% if product.id %}
            <button type="button" 
                    class="btn mt-2 toggle-variant-btn" 
                    data-url="" 
                    data-active="">
            </button>
            <button type="button" 
                    class="btn {% if product.active %}btn-danger{% else %}btn-success{% endif %} mt-2 toggle-product-btn" 
                    data-url="{% url 'product_deactivate' pk=product.id %}" 
                    data-active="{{ product.active|yesno:'true,false' }}">
                {% if product.active %}Deactivate Product{% else %}Activate Product{% endif %}
            </button>
        {% endif %}
    </div>   
    {% else %}
    <a id="edit-link-{{ product.id }}"
        href="{% url 'product_detail' slug=product.slug %}?size={{ product_data.variant_size }}#"
        class="btn btn-secondary {% if view == 'list' %}btn-sm{% else %}btn-buy{% endif %}"
        data-base-url="{% url 'product_detail' slug=product.slug %}">
        Edit
    </a>
    {% endif %}
{% else %}
    <input id="buy-button-{{ product.id }}" 
        type="button" 
        class="btn btn-secondary btn-buy {% if view == 'list' %}btn-sm{% endif %} {% if default_stock_status == 'Out of Stock' %}disabled{% endif %}"
        value="Buy"
        data-url="{% url 'add_to_cart' product.id %}" 
        data-product-id="{{ product.id }}">
{% endif %}

product/templates/product/includes/badge.html
<!-- Badges -->
<div class="badge-container position-absolute top-0 start-0 p-2">
    <span id="badge-product-{{ product.id }}" class="badge badge-{% if product.active %}active">Product: Active{% else %}inactive">Product: Inactive{% endif %}</span>
    <span id="badge-size-{{ product.id }}" class="badge badge-{% if product_data.size_active %}active">Size: Active{% else %}inactive">Size: Inactive{% endif %}</span>
</div>

product/templates/product/includes/catalog.html
{% load static %}
{% include 'store/includes/filter-sort.html' %}

<!-- Products Grid -->
<div class="row g-4">
    {% for product_data in products_with_context %}
    <div class="col-12 col-md-4 col-lg-3 d-flex justify-content-center align-items-center">
        {% include 'product/includes/product_card.html' with view='list' product=product_data.product image=product_data.image %}
    </div>
    {% empty %}

    <p>No products match the selected filters.</p>
    {% endfor %}
</div>

<!-- Page specific scripts -->
<script src="{% static 'js/product.js' %}" defer></script>

product/templates/product/includes/description.html
{% if view == 'detail' %}
    {% if is_admin %}
        {{ product_form.description|as_crispy_field }}
    {% else %}
        <p class="form-label">
            Description
        </p>
        <p class="card-text mx-auto {% if view == 'detail' %}text-start{% endif %}" id="description">
            {{ product.description }}
        </p>
    {% endif %}
{% else %}
    <p class="card-text mx-auto mt-2">
        {{ product.description }}
    </p>
{% endif %}

product/templates/product/includes/image.html
{% load static %}
<div class="{% if view == 'detail' %}col-md-6 d-flex align-items-center justify-content-center{% else %}background-gradient{% endif %} position-relative">
    <div class="{% if view == 'detail' %}card card-image-detail{% endif %}">
        <div class="{% if view == 'detail' %}background-gradient{% endif %} border-radius">
            <div class="content-gradient">
                {% if is_admin and product.id %}
                    {% include 'product/includes/badge.html' %}
                {% endif %}

                <!-- Product Image -->
                <img id="product-image-{{ product.id }}" 
                class="card-img-top deferred-image"
                data-src="{{ image }}"
                src="{% static 'images/product-holder.webp' %}"
                alt="{{ product.name }}"
                loading="lazy">
            </div>
        </div>

        <!-- Image Upload Icon for Superusers -->
        {% if is_admin and view == 'detail' %}
            <div class="image-upload-icon menu-icon position-absolute">
                <label for="id_image_path" class="sr-only">Change Product Image</label>
                <input id="id_image_path" 
                       type="file" 
                       name="image_path" 
                       class="form-control d-none"
                       onchange="previewImage(this, 'product-image-{{ product.id }}')">
                <i class="fa-solid fa-upload upload-icon menu-item"
                    tabindex="0"
                    role="button"
                    aria-label="Upload file"
                    onclick="document.getElementById('id_image_path').click()"
                    onkeydown="if(event.key === 'Enter' || event.key === ' ') document.getElementById('id_image_path').click()">
                </i>
            </div>
        {% endif %}
    </div>
</div>

product/templates/product/includes/name.html
{% if view == 'detail' %}
    {% if is_admin %}
        {{ product_form.name|as_crispy_field }}
    {% else %}
        <h2 class="card-title">
            {{ product.name }}
        </h2>
    {% endif %}
{% else %}
    <h2 class="card-title mx-auto">
        <a id="detail-link-{{ product.id }}"
            href="{% url 'product_detail' slug=product.slug %}?size={{ product_data.variant_size }}">
            {{ product.name }}
        </a>
    </h2>
{% endif %}

product/templates/product/includes/price.html
<!-- Price or Stock Status -->
{% if is_admin and view == 'detail'%}
    <div class="col-md-6 mx-auto selector-group">
        {{ variant_form.price|as_crispy_field }}
    </div>
{% else %}
    <h3 class="card-subtitle mt-2" id="price-{{ product.id }}">
        {% if default_stock_status == 'Out of Stock' %}
            <span class="text-danger"><strong>Out of Stock</strong></span>
        {% else %}
            <span><strong>${% if view == 'list' %}{{ product_data.variant_price }}{% else %}{{ default_price }}{% endif %} <span>each</span></strong></span>
        {% endif %}
    </h3>
{% endif %}

product/templates/product/includes/product_card.html
{% load static %}
{% load crispy_forms_tags %}
{% load i18n %}

{% if is_admin %}
<form class="form w-100 {% if view != 'detail' %}card{% endif %}">
    {% csrf_token %}
{% endif %}
    <div class="product-card {% if view == 'detail' %}container mt-5 product-page page-container{% elif not is_admin %}card{% endif %} w-100">
        <div class="{% if view == 'detail' %}row{% endif %}">
            
            <!-- Product Image -->
            {% include 'product/includes/image.html' %}

            <!-- Product details -->
            <div class="{% if view == 'detail' %}col-md-6 p-4{% else %}card-body p-2{% endif %}">
                <!-- Name -->
                {% include 'product/includes/name.html' %}

                <!-- Review Stars -->
                {% if not is_admin %}
                    {% include 'product/includes/review_stars.html' %}
                {% elif view == 'list' %}
                    {% include 'product/includes/review_stars.html' %}
                {% endif %}

                <!-- Description -->
                {% include 'product/includes/description.html' %}

                <!-- Size and Quantity/Stock -->
                <div class="row g-3 align-items-end {% if view == 'detail' %}selectors-row{% else %}card-row{% endif %}">
                    <!-- Size -->
                    {% if product.id %}
                        {% if view == 'list' %}
                            {% include 'product/includes/selector.html' with type="size" items=product_data.stock_by_size.items selected_value=product_data.variant_size %}
                        {% else %}
                            {% include 'product/includes/selector.html' with type="size" items=stock_by_size.items selected_value=default_size %}
                        {% endif %}
                    {% endif %}

                    {% if not is_admin or view == 'list' %}
                        {% if product.id %}
                            <!-- Quantity/Stock Selector -->
                            {% include 'product/includes/quantity_stock.html' %}
                        {% endif %}
                    {% else %}
                        <!-- Category -->
                        {% include 'product/includes/selector.html' with type="category" items=category_items selected_value=selected_category %}
                    {% endif %}
                </div>

                {% if product.id %}
                    <!-- Price -->
                    {% if not is_admin or view == 'list' %}
                        {% include 'product/includes/price.html' %}
                    {% else %}
                        <div class="row g-3 align-items-end {% if view == 'detail' %}selectors-row{% else %}card-row{% endif %}">
                            {% include 'product/includes/price.html' %}
                            {% include 'product/includes/quantity_stock.html' %}
                        </div>
                    {% endif %}
                {% endif %}

                <!-- Buttons -->
                {% include 'product/includes/actions.html' %}
                
                {% if product.id %}
                    <!-- Review form -->
                    {% include 'product/includes/review_form.html' %}
                {% endif %}
            </div>

            {% if product.id %}
                <!-- Review history -->
                {% include 'product/includes/review_history.html' %}
            {% endif %}
        </div>
    </div>
    <input type="hidden" name="redirect_url" value="{{ request.path }}">

{% if is_admin %}
</form>
{% endif %}

product/templates/product/includes/quantity_stock.html
{% if is_admin and view == 'detail' %}
    <div class="col-md-6 mx-auto selector-group">
        {{ variant_form.stock|as_crispy_field }}
    </div>
{% else %}
    <div class="col-md-6 mx-auto {% if view == 'detail' %}selector-group{% else %}mt-2{% endif %}">
        <label for="{% if is_admin %}stock-select-{% else %}quantity-select-{% endif %}{% if view == 'detail' %}{{ product.id }}{% else %}{{ product.id }}{% endif %}" 
            class="form-label {% if view == 'detail' %}selector-label{% endif %}">
            {% if is_admin %}Stock{% else %}Quantity{% endif %}
        </label>
        <input id="{% if is_admin %}stock-select-{% else %}quantity-select-{% endif %}{% if view == 'detail' %}{{ product.id }}{% else %}{{ product.id }}{% endif %}" 
            type="number" 
            class="form-control quantity mt-1 {% if view == 'detail' %}selector-input{% endif %}"
            min="1" 
            {% if not is_admin %}max="{% if view == 'detail' %}{{ default_stock }}{% else %}{{ product_data.variant_stock }}{% endif %}"{% endif %}
            value="{% if is_admin and view == 'detail' %}{{ default_variant.stock|default:0 }}{% elif is_admin and view != 'detail' %}{{ product_data.variant_stock|default:0 }}{% else %}1{% endif %}"
            name="{% if is_admin %}stock{% else %}quantity{% endif %}"
            {% if view != 'detail' and is_admin %}disabled{% endif %}>
    </div>
{% endif %}

product/templates/product/includes/review_form.html
{% load crispy_forms_tags %}

{% if view == 'detail' %}
<div class="mt-3 card-body rating-container mt-5">
    {% if not is_admin %}
        <form method="POST" class="rating-form">
            {% csrf_token %}
            <!-- Clickable Star Rating -->
            <div id="star-rating" class="mt-3 mb-3 centered-element">
                <!-- Hidden Rating Input (not displayed) -->
                <div class="sr-only">
                    <label for="id_rating" class="sr-only">Rating</label>
                    {{ review_form.rating }}
                    <small id="id_rating_helptext">
                        Select your rating from 0 to 5.
                    </small>
                </div>
                {% for star in max_review %}
                    <svg class="star icon icon-coffee-bean {% if star < rating %}filled{% endif %}" data-value="{{ forloop.counter }}"><use xlink:href="#icon-coffee-bean"></use></svg>
                {% endfor %}
            </div>

            <div class="row">
                <div class="col-9">
                    {{ review_form.comment|as_crispy_field }}
                </div>
                <div class="col-3">
                    <button type="submit" class="btn btn-sm btn-primary col btn-review">
                        <i class="fa-solid fa-paper-plane"></i>
                        <span class="sr-only">Send</span>
                    </button>
                </div>
            </div>
        </form>
    {% endif %}
</div>
{% endif %}

product/templates/product/includes/review_stars.html
<div class="review-stars">
    {% with product.rating as rating %}
        {% for star in max_review %}
            <svg class="star icon icon-coffee-bean {% if star < rating %}filled{% endif %}"><use xlink:href="#icon-coffee-bean"></use></svg>
        {% endfor %}
    {% endwith %}
    <p class="text-muted">({{ product.rating }})</p>
</div>